name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "239ac1d1-36ad-431b-b23b-f9bb06f21765" \
            --password "Eih8Q~QVHMwMXrdn--j_ti5RH7nL7LsPzEsLpbpp" \
            --tenant "44ff9492-6357-4790-9759-8d5b4666c643"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "f506e9ea-7a47-4c62-82ac-24efcf83b366"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: Environment/Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
           --service-principal \
            --username "239ac1d1-36ad-431b-b23b-f9bb06f21765" \
            --password "Eih8Q~QVHMwMXrdn--j_ti5RH7nL7LsPzEsLpbpp" \
            --tenant "44ff9492-6357-4790-9759-8d5b4666c643"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "f506e9ea-7a47-4c62-82ac-24efcf83b366"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan